### ISSUE TITLE
Make distributed functionality optional

### ISSUE THREAD

**Issue by baggepinnen** [ymtoo/AcousticFeatures.jl#4]
I noticed that this package automatically create workers through
```
addprocs(length(Sys.cpu_info())-1)
```
upon loading. This will create problems if the user
- Already has workers started
- Has small amount of RAM

Another strategy is to allow the user to change the ``map`` function in the function that could benefit from distributed computing, like this
```julia
Score(f, x...; map = map)
```
so the user can call it with
```julia
Score(f, x...; map = pmap)
```
after manually having started workers. This would also allow the user to use, e.g., `tmap` from [ThreadTools.jl](https://github.com/baggepinnen/ThreadTools.jl).

**Comment by ymtoo** [comment]
Sounds good. For the keyword argument naming conventions, is it OK to overload `map` with `map = pmap` or `map = tmap`?

**Comment by baggepinnen** [comment]
Yes, if you introduce a keyword `map` it locally shadows the function with the same name and you can pass in any function in its place.
